### PR TITLE
sirv-cli: expose option clear to CLI as --noclear

### PR DESCRIPTION
**Pull request by milahu**
part of issue #17 

console clearing is really annoying, when sirv runs after a bundler like rollup
since the last ~20 lines of the terminal are overwritten by the sirv-cli screen
and warning messages from the bundler are lost

now we can call `npx sirv www/ --noclear` to disable console-clearing alltogether

### CODE REVIEW

**Comment by lukeed** [comment]
Hi, you can already do `--no-clear`

**Comment by milahu** [comment]
aah, fact : ) i was only going by `npx sirv --help` where that flag is not listed

**Comment by lukeed** [comment]
Yeah it's been raised before but I don't want it listed in the help text. Am fine with a readme addition though.

**Comment by milahu** [comment]
> I don't want it listed in the help text

hmm : /

as i said, its \*really\* annoying, when my bundler prints a warning message
which is removed by sirv's fancy "Your application is ready" screen

`clear(true)` is supposed to preserve the terminal history
but when the last 20 lines are still removed, its rather useless
(sounds like a bug in the terminal library)

**Comment by lukeed** [comment]
The option exists to disable it. It's just a documentation issue.

It's non-standard to list `--no-*` flags in any help text. Plus I don't like it, which is why it's unlisted. 
Everyone has their own preferences as to what _should_ happen with clearing. I've heard every argument over the lifetime of this project. Options are there to override the defaults.

Thank you though

**Comment by milahu** [comment]
> It's non-standard to list `--no-*` flags in any help text.

1\. screw "the standard"
2\. we could call it `--keephistory`

> Plus I don't like it, which is why it's unlisted.

probably cos its shows an underlying bug in the terminal library = out of scope

thanks for the chat : )

**Comment by milahu** [comment]
... and once again i have to ask google on "how to stop sirv from clearing my console",
cos `--no-clear` is not in the help text and clearing is default on -__-

**Pull request closed without merging**
