### PR TITLE
fix #7 serve sub directory in windows

### LINKED ISSUE #7: Unable to serve sub directory in windows
current version only able to serve file on root directory as the file separator in windows different with req.pathname

expected FILES mapping
```{ "/img/logo.png": "public\\img\\logo.png'}```
actually
```{ "/img\\logo.png": "public\\img\\logo.png'}```

### PR DESCRIPTION
**Pull request by antonheryanto**
fix #7 
current version only able to serve file on root directory as the file separator in windows different with req.pathname

### CODE REVIEW

**Comment by lukeed** [comment]
Thanks @antonheryanto! Can you give this a try for me instead? It should still do the trick. The difference is that it'll allow _multiple_ subdirectories, as well as replace both `\` and `\\` separators on Windows.

**Comment by lukeed** [comment]
Updated the RegExp since there's only a need to change Windows' pathing.

**Comment by antonheryanto** [comment]
thanks for the great project and faster reply.

i have tested and work correctly

**Comment by lukeed** [comment]
Awesome, thank you~!

**Pull request merged**
