### PR TITLE
Add local network info (#70)

### LINKED ISSUE #70: Can't access server over local network
When I launch a server via sirv-cli, I can't access that server from another computer on the local network. I put together [this reproduction repo](https://github.com/mhkeller/test-server) so you can see how this issue doesn't occur with two other libraries. 

I tried it with `-c` and `--cors` but that didn't fix it. If I manually set the local ip address via `-H` that does fix it.

### PR DESCRIPTION
**Pull request by mhkeller**
Per https://github.com/lukeed/sirv/issues/70, adds documentation and a notice to the CLI text output telling users how to expose the server on the local network.

If nothing is specified, the user gets a notice:

Screen Shot 2020-06-26 at 5 14 11 PM

If `-H` is specified, the behavior remains the same as it is now:

with-flag

---

Closes #70

### CODE REVIEW

**Comment by lukeed** [comment]
Thanks :) Fiddling a little bit with it, as promised haha. How're these?

Screen Shot 2020-06-26 at 3 09 43 PM

Screen Shot 2020-06-26 at 3 11 01 PM

I'm leaning towards the second

**Comment by mhkeller** [comment]
Looks good. I prefer the second one as well.

**Comment by mhkeller** [comment]
The gray is a real nice addition btw!

**Comment by lukeed** [comment]
Thanks, I fixate on the wrong things, but sometimes it pans out 😆

**Comment by mhkeller** [comment]
The readme addition looks really good! Nice idea to add that!

**Comment by lukeed** [comment]
Published as [1.0.2](https://github.com/lukeed/sirv/releases/tag/v1.0.2) -- thanks again :)

**Pull request merged**
